import type { Theme } from '../../types/theme';

export const githubDark: Theme = {
  id: 'github-dark',
  name: 'GitHub Dark',
  author: 'GitHub',
  isPreset: true,
  isReadOnly: true,
  colors: {
    bg: {
      base: '#24292e',
      elevated: '#1f2428',
      overlay: '#2f363d',
      input: '#24292e',
      tooltip: '#1f2428',
    },
    surface: {
      primary: '#1f2428',
      secondary: '#2f363d',
      tertiary: '#444d56',
      hover: '#2f363d',
      active: '#0366d6',
      disabled: '#1f2428',
    },
    text: {
      primary: '#f6f8fa',
      secondary: '#959da5',
      muted: '#6a737d',
      disabled: '#444d56',
      accent: '#0366d6',
      inverse: '#24292e',
    },
    accent: {
      primary: '#0366d6',
      secondary: '#b392f0',
      success: '#28a745',
      warning: '#fb8532',
      error: '#ea4a5a',
      info: '#79b8ff',
    },
    border: {
      subtle: '#1f2428',
      default: '#444d56',
      strong: '#6a737d',
      focus: '#0366d6',
    },
    semantic: {
      string: '#79b8ff',
      number: '#c8e1ff',
      boolean: '#b392f0',
      date: '#7bcc72',
      null: '#6a737d',
      primaryKey: '#fb8532',
      foreignKey: '#79b8ff',
      index: '#b392f0',
      connectionActive: '#28a745',
      connectionInactive: '#6a737d',
      modified: '#0366d6',
      deleted: '#d73a49',
      new: '#28a745',
    },
  },
  typography: {
    fontFamily: {
      base: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif',
      mono: 'SFMono-Regular, Consolas, Liberation Mono, Menlo, monospace',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
    },
  },
  layout: {
    borderRadius: {
      sm: '0.25rem',
      base: '0.5rem',
      lg: '0.75rem',
      xl: '1rem',
    },
    spacing: {
      xs: '0.25rem',
      sm: '0.5rem',
      base: '1rem',
      lg: '1.5rem',
      xl: '2rem',
    },
  },
  monacoTheme: {
    base: 'vs-dark',
    inherit: true,
    themeName: 'GitHub Dark',
    rules: [
      { token: 'comment', foreground: '959DA5' },
      { token: 'keyword', foreground: 'EA4A5A' },
      { token: 'string', foreground: '79B8FF' },
      { token: 'number', foreground: 'C8E1FF' },
      { token: 'regexp', foreground: '79B8FF' },
      { token: 'operator', foreground: 'EA4A5A' },
      { token: 'namespace', foreground: 'EA4A5A' },
      { token: 'type', foreground: 'FB8532' },
      { token: 'struct', foreground: 'FB8532' },
      { token: 'class', foreground: 'FB8532' },
      { token: 'interface', foreground: 'FB8532' },
      { token: 'enum', foreground: 'FB8532' },
      { token: 'typeParameter', foreground: 'FB8532' },
      { token: 'function', foreground: 'B392F0' },
      { token: 'member', foreground: 'B392F0' },
      { token: 'macro', foreground: 'B392F0' },
      { token: 'variable', foreground: 'F6F8FA' },
      { token: 'parameter', foreground: 'F6F8FA' },
      { token: 'property', foreground: 'F6F8FA' },
      { token: 'label', foreground: 'EA4A5A' },
    ],
    colors: {
      'editor.background': '#24292E',
      'editor.foreground': '#F6F8FA',
      'editorLineNumber.foreground': '#6A737D',
      'editorLineNumber.activeForeground': '#F6F8FA',
      'editor.selectionBackground': '#4C2889',
      'editor.selectionHighlightBackground': '#444D56',
      'editor.wordHighlightBackground': '#444D56',
      'editor.wordHighlightStrongBackground': '#444D56',
      'editor.findMatchBackground': '#FB8532',
      'editor.findMatchHighlightBackground': '#B08800',
      'editor.findRangeHighlightBackground': '#444D56',
      'editor.hoverHighlightBackground': '#444D56',
      'editorCursor.foreground': '#FFFFFF',
      'editorIndentGuide.background': '#6A737D',
      'editorIndentGuide.activeBackground': '#F6F8FA',
      'editorLineHighlightBackground': '#444D56',
      'editorLink.activeForeground': '#0366D6',
    },
  },
};
